// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropostasApi.Dominio;

#nullable disable

namespace PropostasApi.Migrations
{
    [DbContext(typeof(PropostasDbContext))]
    [Migration("20241028003406_segndaMigration")]
    partial class segndaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropostasApi.Dominio.Proposta.Agente", b =>
                {
                    b.Property<string>("CodigoAgente")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.HasKey("CodigoAgente");

                    b.ToTable("Agentes", (string)null);
                });

            modelBuilder.Entity("PropostasApi.Dominio.Proposta.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Complemento")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("PropostasApi.Dominio.Proposta.Pessoa", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("VARCHAR(11)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("DATE");

                    b.HasKey("Cpf");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("PropostasApi.Dominio.Proposta.PropostaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agente")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Conveniada")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rendimento")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.Property<int>("TipoAssinatura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("PropostasCredito", (string)null);
                });

            modelBuilder.Entity("PropostasApi.Dominio.Proposta.PropostaCredito", b =>
                {
                    b.HasOne("PropostasApi.Dominio.Proposta.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
